app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()

class Character(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    movie = db.Column(db.String(50))
    genre = db.Column(db.String(50), nullable=True, default='Unknown')
    rating = db.Column(db.String(50), nullable=True, default='Unknown')
    year = db.Column(db.Integer, nullable=True, default='Unknown')
    name = db.Column(db.String(50), nullable=False, unique=True)

    def __repr__(self):
        return f"<Character: {self.name}>"

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), nullable=False, unique=True)
    email = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String(20), nullable=False)

    def __init__(self, username, password, email):
        self.username = username
        self.password = password
        self.email = email
    
    def __repr__(self):
        return f"<User: {self.username}>"

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo

class newCharacterForm(FlaskForm):
    movie = StringField('Movie')
    genre = StringField('Genre')
    rating = StringField('Rating')
    year = IntegerField('Year')
    name = StringField('Name', validators=[DataRequired()])
    submit_button = SubmitField()

class newUserForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit_button = SubmitField()
    
class loginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_button = SubmitField()

app/__init__.py
from flask import Flask
from config import Config

from .site.routes import site 
from .authentication.routes import auth

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from .models import db

app = Flask(__name__) 

app.register_blueprint(site)
app.register_blueprint(auth)

app.config.from_object(Config)

db.init_app(app)

migrate = Migrate(app,db)


from . import models

app/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import check_password_hash

auth = Blueprint('auth', __name__, template_folder='auth_templates')

from app.forms import newUserForm, loginForm

from app.models import User, db

@auth.route('/signup', methods=['GET','POST'])
def signup():
    form = newUserForm()
    if request.method=='POST' and form.validate_on_submit():
        usernamedata = form.username.data
        emaildata = form.email.data
        passworddata = form.password.data

        new_user = User(usernamedata, passworddata, emaildata)

        db.session.add(new_user)
        db.session.commit()

        flash(f'You have successfully signed up with the username : {usernamedata}!')

        return redirect(url_for('auth.signin'))


    return render_template('signup.html', form = form)

@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    f = loginForm()
    if request.method == 'POST' and f.validate_on_submit():
        usernamedata = f.username.data
        passworddata = f.password.data
        
        user = User.query.filter_by(username=usernamedata).first()
        if user is None or check_password_hash(user.password, passworddata):
            flash(f'Incorrect username or password')
            return redirect(url_for('auth.signin'))
        
        login_user(user)
        flash(f'You have successfully signed in! Welcome {usernamedata}')
        return redirect(url_for('site.home'))


    return render_template('signin.html', form = f)

@auth.route('/signout', methods=['GET'])
def signout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for

from flask_login import current_user, login_required

# import any database model we're using
from app.models import Character, db

# import our form that we're using
from app.forms import newCharacterForm
site = Blueprint('site', __name__, template_folder='site_templates')

#homepage route
@site.route('/', methods=['GET', 'POST'])
def home():
    form = newCharacterForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            moviedata = form.movie.data
            genredata = form.genre.data
            ratingdata = form.rating.data
            yeardata = form.year.data
            namedata = form.name.data

            print(moviedata, namedata)

            new_character = Character(movie=moviedata,genre=genredata, rating=ratingdata, year=yeardata, name=namedata)

            db.session.add(new_character)
            db.session.commit()

            #flash messages 
            flash(f'You have successfully added the character {namedata} to your database.')

            return redirect(url_for('site.home'))
    except:
        flash(f'Invalid form input, try again.')
        return redirect(url_for('site.home'))
    return render_template('index.html',form=form)    

#profile
@site.route('/profile')
def profile():
    return render_template('profile.html') 

@site.route('/character')
def displayCharacter():
    c = Character.query.all()
    return render_template('display_character.html', Character=c)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here" />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="../static/css/main.css">
    <title>Disney Character API</title>
</head>

<body>
    {% block example %}
    {% endblock example %}

    <!--NavBar Here-->
    <nav class="ct-nav">
        <div>
            <img src="../../static/images/Disney Logo.png" alt="Disney Logo">
        </div>

        <!--Nav Items-->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Disney Project</li>
                </a>
            
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                <!--User Auth Check for SignIn/SignUp Nav Buttons-->


                <a href="">
                    <li>Sign Out</li>
                </a>

                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up Free</li>
                </a>
                <a href="{{ url_for('site.displayCharacter') }}">
                    <li>List of Characters</li>
                </a>

            </ul>
        </div>
    </nav>
    <!--End of Nav-->
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <!-- b4-alert-closable -->
        <div class="alert alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
</div>

    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"></script>
</body>

</html>

app/templates/forms.html
<!-- HTML structure of this form as suggested by WTForms -->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="movie-field">
            {{ form.movie.label }}
            {{ form.movie(class = "form-control", placeholder = "Movie name...")}}
        </fieldset>
        <fieldset id="genre-field">
            {{ form.genre.label }}
            {{ form.genre(class = "form-control", placeholder = "Genre Type...")}}
        </fieldset>
        <fieldset id="rating-field">
            {{ form.rating.label }}
            {{ form.rating(class = "form-control", placeholder = "Moving Rating...")}}
        </fieldset>
        <fieldset id="year-field">
            {{ form.year.label }}
            {{ form.year(class = "form-control", placeholder = "Release Year")}}
        </fieldset>
        <fieldset id="name-field">
            {{ form.name.label }}
            {{ form.name(class = "form-control", placeholder = "Character Name")}}
        </fieldset>
        <!--Submit Button Area-->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>